# YAML configuration for motors 0-3
#
#   +---------+------------+----------------+------------+----------------+--------------+----------------+
#   | Motor   | PWM Out    | Direction GPIO | Encoder In | PWM Timer / Ch | Dir Pin Type | Enc Timer / Ch |
#   +---------+------------+----------------+------------+----------------+--------------+----------------+
#   | Motor 0 | PB6        | B12            | C6         | TIM4_CH1       | GPIO         | TIM3_CH1       |
#   | Motor 1 | PB7        | B14            | C7         | TIM4_CH2       | GPIO         | TIM3_CH2       |
#   | Motor 2 | PB8        | B3             | C8         | TIM4_CH3       | GPIO         | TIM3_CH3       |
#   | Motor 3 | PB9        | B5             | C9         | TIM4_CH4       | GPIO         | TIM3_CH4       |
#   +---------+------------+----------------+------------+----------------+--------------+----------------+
#

kros:
    i2c_slave:
        i2c_id:                     1
        i2c_address:             0x43
    motor_controller:
        rpm_timer_number:           2   # RPM timer number
        rpm_timer_frequency:      100   # RPM timer frequency in Hz
        pwm_frequency:          20000   # frequency for PWM to motors (20-30kHz)
        encoder_frequency:        100   # encoder frequency in Hz
        log_timer_number:           6   # log timer number
        log_timer_frequency:       20   # log timer frequency in 20Hz (50ms period)
        
    motors:
        motor0:
            name:                'M0'
            pwm_timer:              4
            pwm_channel:            1
            pwm_pin:             'B6'
            pwm_pin_name:       'PB6'
            direction_pin:      'B12'
            direction_pin_name: 'B12'
            encoder_pin:         'C6'
            encoder_pin_name:   'PC6'
            enc_timer:              3
            enc_channel:            1
            reverse:            False
        motor1:
            name:                'M1'
            pwm_timer:              4
            pwm_channel:            2
            pwm_pin:             'B7'
            pwm_pin_name:       'PB7'
            direction_pin:      'B14'
            direction_pin_name: 'B14'
            encoder_pin:         'C7'
            encoder_pin_name:   'PC7'
            enc_timer:              3
            enc_channel:            2
            reverse:             True
        motor2:
            name:                'M2'
            pwm_timer:              4
            pwm_channel:            3
            pwm_pin:             'B8'
            pwm_pin_name:       'PB8'
            direction_pin:       'B3'
            direction_pin_name:  'B3'
            encoder_pin:         'C8'
            encoder_pin_name:   'PC8'
            enc_timer:              3
            enc_channel:            3
            reverse:            False
        motor3:
            name:                'M3'
            pwm_timer:              4
            pwm_channel:            4
            pwm_pin:             'B9'
            pwm_pin_name:       'PB9'
            direction_pin:       'B5'
            direction_pin_name:  'B5'
            encoder_pin:         'C9'
            encoder_pin_name:   'PC9'
            enc_timer:              3
            enc_channel:            4
            reverse:             True

#EOF
